seedbox42:
    restart: always
    build: seedbox42
    net: torrent
    volumes:
        - ./downloads:/seedbox42
    environment:
        - pwd
    ports:
        - "4242:3000"
    container_name: seedbox42

mongodb:
    restart: always
    net: torrent
    build: mongodb
    container_name: mongodb

